sudo: required

services:
  - docker

script:

 - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind casperyo/latex-docker
  /bin/sh -c "pdflatex main.tex"

 #- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  #/bin/sh -c "tectonic --keep-intermediates --reruns 0 main.tex; biber main; tectonic main.tex"
  
deploy:
    provider: releases
    api_key:
        secure: $GH_TOKEN
    file: 
    - $TRAVIS_BUILD_DIR/main.pdf
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
